Pin to PySide2>=5.12.0,<=5.14.1
PySide2 5.14.2 is causing weird errors (at least when running
tests) such has:

SystemError: <class 'GeneratorExit'> returned a result with an error set