Allow max tracking args for Kalman filter (#1986)
* and note where `target_instance_count` is initialized

* `target_instance_count` is not available in the GUI but `max_tracks` is

* add note where `target_instance_count` is initialized

* add note since neither `target_instance_count` nor `pre_cull_to_target` are options in the GUI

* accept either max_tracks or target_instance_count for compatibility with both CLI and GUI

* TypeError: track() got an unexpected keyword argument 'img_hw' since `init_tracker` has `img_hw`

* useful print statements

* black

* np.bool is deprecated

* debug

* add params for testing kalman filter

* remove params because this function isn't used

* debugging

* test kalman filter tracking

* add documentation

* kalman filter needs node indices, simple tracking and similarity anything besides normalized

* add tests for every combination related to kalman args

* add example to documentation

* delete debug scripts

* delete print statements

* black

* add test for connect single breaks